### ISSUE TITLE
Doesn't work with ReadyNASOS-6.8.0-RC1-x86_64

### ISSUE THREAD

**Issue by grtessman** [Mhynlo/readynas-docker-cli#3]
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: fv-app-install (/tmp/docker-cli-rnapp_17.06.0_amd64.deb): error code [100]: Reading package lists...
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: Building dependency tree...
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: Reading state information...
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: Some packages could not be installed. This may mean that you have
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: requested an impossible situation or if you are using the unstable
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: distribution that some required packages have not yet been created
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: or been moved out of Incoming.
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: The following information may help to resolve the situation:
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: The following packages have unmet dependencies:
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]:  docker-cli-rnapp : Depends: linux-image-extra but it is not going to be installed
Aug 10 18:26:30 ReadyNAS1 fv-app-install[13128]: E: Unable to correct problems, you have held broken packages.
Aug 10 18:26:31 ReadyNAS1 fv-app-install[13128]: [docker-cli-rnapp](0%) abort
Aug 10 18:26:31 ReadyNAS1 readynasd[3984]: spooler (pid=13124) returns spool_status=1 outbuf=(null) errbuf=(null) is_localapp=1 name=docker-cli-rnapp pkgname=docker-cli-rnapp

**Comment by Mhynlo** [comment]
It does require `linux-image-extra` to be on the readynas servers. I am not sure how it would work on the RC1 build, but it seems to be working for me on the 6.8.0 release build.
Can you try that firmware first?
https://community.netgear.com/t5/ReadyNAS-Firmware-Release-Notes/ReadyNAS-OS-6-8-0-now-available/td-p/1343620

**Comment by grtessman** [comment]
Yes it works with 6.8.0.  Sorry, I didn't know that was out yet else I would have tried it.  Thank you so much! PS - Are you aware of Kitematic or anything for this as well to manage these in a web gui from a remote server?
